spring.application.name=spotify-card
lastfm.api.key=${LASTFM_API_KEY}
lastfm.api.url=https://ws.audioscrobbler.com/2.0
logging.level.org.springframework.web=DEBUG
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=30s